feat/928-Removed check and fix commands
datacoves/dbt-coves pull request #225
Opened 2022-07-19 23:25 UTC by BAntonellini

2022-07-20 21:22 UTC, noel requested changes

2022-07-20 21:22 UTC, ssassi commented on pyproject.toml
>  cookiecutter = "^1.7.3"
Yes, we can remove it.

2022-07-20 21:23 UTC, ssassi commented on pyproject.toml
>  dbt-core = ">=0.18.0,<2.0.0"
Agree

2022-07-21 15:57 UTC, BAntonellini commented on pyproject.toml
>  dbt-core = ">=0.18.0,<2.0.0"
@ssassi @noel `sqlfluff-templater-dbt` is one of the removed packages (alongside sqlfluff and pre-commit)

what do you mean by `doing >=1.0.0`

2022-07-21 16:12 UTC, ssassi commented on pyproject.toml
>  dbt-core = ">=0.18.0,<2.0.0"
dbt-core = ">=1.0.0,<2.0.0"

2022-07-21 16:14 UTC, BAntonellini commented on pyproject.toml
>  dbt-core = ">=0.18.0,<2.0.0"
Thought he referred to sqlfluff-templater-dbt

done

2022-07-21 16:30 UTC, noel commented on pyproject.toml
>  dbt-core = ">=0.18.0,<2.0.0"
the comment was against the dbt-core line :)

2022-07-22 13:13 UTC, merged